version: '3.3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: electric_scooters
    volumes:
      - ./docker/volumes/datadir:/var/lib/mysql mysql
    ports:
      - 3307:3306

  service:
    image: app1
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST:
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_DB: electric_scooters